[build]
command = "npm run build"
publish = "public"

[functions]
node_bundler = "esbuild"

# Всі маршрути йдуть на сервер Remix (який генерує адаптер)
[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"
